version: "3"
services:
  app:
    build: ./product-service
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  front-end:
        image: php:apache
        volumes:
          - ./front-end/src:/var/www/html
        ports:
          - 3001:80
        depends_on:
          - app
